### ISSUE TITLE
Document is not working

### ISSUE THREAD

**Issue by multijump** [bttcprotocol/launch#15]
Hi

I am installing bttc node in my server.
But I am getting 404 error when I visit to your documents.
https://doc.bt.io/v1/doc/node

<img width="1737" alt="image" src="https://user-images.githubusercontent.com/35476479/196957562-507c6879-676c-4e00-bde1-21750d1d3c21.png">

Thanks.

**Comment by ethan1844** [comment]
Please refer to here to install bttc: https://doc.bt.io/docs/node/build-fullnode

**Comment by multijump** [comment]
> https://doc.bt.io/docs/node/build-fullnode

Thanks.
It works.
