### ISSUE TITLE
bttc seed nodes incorrect

### ISSUE THREAD

**Issue by mjay0** [bttcprotocol/launch#2]
the mainnet bttc seed nodes are incorrect (seed nodes are for network id 1029, not for mainnet 199):
```
DEBUG[12-13|19:30:48.016] Adding p2p peer                          peercount=1 id=114411605d6120c1 conn=dyndial addr=107.20.250.182:30303 name=bor/v0.2.8-stable-e2...
DEBUG[12-13|19:30:48.016] Adding p2p peer                          peercount=2 id=f724c19b63e0529a conn=dyndial addr=54.157.35.210:30303  name=bor/v0.2.8-stable-e2...
DEBUG[12-13|19:30:48.097] Ethereum handshake failed                id=114411605d6120c1 conn=dyndial err="network ID mismatch: 199 (!= 1029)"
DEBUG[12-13|19:30:48.097] Message handling failed in `snap`        peer=11441160 err=EOF
DEBUG[12-13|19:30:48.097] Removing p2p peer                        peercount=1 id=114411605d6120c1 duration=81.316ms req=false err="network ID mismatch: 199 (!= 1029)"
DEBUG[12-13|19:30:48.098] Message handling failed in `snap`        peer=f724c19b err=EOF
DEBUG[12-13|19:30:48.098] Ethereum handshake failed                id=f724c19b63e0529a conn=dyndial err="network ID mismatch: 199 (!= 1029)"
DEBUG[12-13|19:30:48.098] Removing p2p peer                        peercount=0 id=f724c19b63e0529a duration=81.547ms req=true  err="subprotocol error"
DEBUG[12-13|19:30:48.148] Adding p2p peer                          peercount=1 id=d5186f408b19f91d conn=dyndial addr=54.219.27.155:30303  name=bor/v0.2.8-stable-e2...
DEBUG[12-13|19:30:48.156] Adding p2p peer                          peercount=2 id=9f7c9fb3fbaa28ea conn=dyndial addr=54.241.235.101:30303 name=bor/v0.2.8-stable-e2...
DEBUG[12-13|19:30:48.295] Ethereum handshake failed                id=d5186f408b19f91d conn=dyndial err="network ID mismatch: 199 (!= 1029)"
DEBUG[12-13|19:30:48.295] Message handling failed in `snap`        peer=d5186f40 err=EOF
DEBUG[12-13|19:30:48.295] Removing p2p peer                        peercount=1 id=d5186f408b19f91d duration=147.327ms req=false err="network ID mismatch: 199 (!= 1029)"
DEBUG[12-13|19:30:48.307] Message handling failed in `snap`        peer=9f7c9fb3 err=EOF
DEBUG[12-13|19:30:48.307] Ethereum handshake failed                id=9f7c9fb3fbaa28ea conn=dyndial err="network ID mismatch: 199 (!= 1029)"
DEBUG[12-13|19:30:48.307] Removing p2p peer                        peercount=0 id=9f7c9fb3fbaa28ea duration=151.450ms req=true  err="subprotocol error"
DEBUG[12-13|19:30:52.267] Removed dead node                        b=13 id=9f7c9fb3fbaa28ea ip=54.241.235.101 checks=0
DEBUG[12-13|19:30:53.901] NTP sanity check done                    drift=5.098972ms
INFO [12-13|19:30:58.375] Looking for peers                        peercount=0 tried=4 static=0

```

**Comment by xq-lu** [comment]
> the mainnet bttc seed nodes are incorrect (seed nodes are for network id 1029, not for mainnet 199):
> 
> ```
> DEBUG[12-13|19:30:48.016] Adding p2p peer                          peercount=1 id=114411605d6120c1 conn=dyndial addr=107.20.250.182:30303 name=bor/v0.2.8-stable-e2...
> DEBUG[12-13|19:30:48.016] Adding p2p peer                          peercount=2 id=f724c19b63e0529a conn=dyndial addr=54.157.35.210:30303  name=bor/v0.2.8-stable-e2...
> DEBUG[12-13|19:30:48.097] Ethereum handshake failed                id=114411605d6120c1 conn=dyndial err="network ID mismatch: 199 (!= 1029)"
> DEBUG[12-13|19:30:48.097] Message handling failed in `snap`        peer=11441160 err=EOF
> DEBUG[12-13|19:30:48.097] Removing p2p peer                        peercount=1 id=114411605d6120c1 duration=81.316ms req=false err="network ID mismatch: 199 (!= 1029)"
> DEBUG[12-13|19:30:48.098] Message handling failed in `snap`        peer=f724c19b err=EOF
> DEBUG[12-13|19:30:48.098] Ethereum handshake failed                id=f724c19b63e0529a conn=dyndial err="network ID mismatch: 199 (!= 1029)"
> DEBUG[12-13|19:30:48.098] Removing p2p peer                        peercount=0 id=f724c19b63e0529a duration=81.547ms req=true  err="subprotocol error"
> DEBUG[12-13|19:30:48.148] Adding p2p peer                          peercount=1 id=d5186f408b19f91d conn=dyndial addr=54.219.27.155:30303  name=bor/v0.2.8-stable-e2...
> DEBUG[12-13|19:30:48.156] Adding p2p peer                          peercount=2 id=9f7c9fb3fbaa28ea conn=dyndial addr=54.241.235.101:30303 name=bor/v0.2.8-stable-e2...
> DEBUG[12-13|19:30:48.295] Ethereum handshake failed                id=d5186f408b19f91d conn=dyndial err="network ID mismatch: 199 (!= 1029)"
> DEBUG[12-13|19:30:48.295] Message handling failed in `snap`        peer=d5186f40 err=EOF
> DEBUG[12-13|19:30:48.295] Removing p2p peer                        peercount=1 id=d5186f408b19f91d duration=147.327ms req=false err="network ID mismatch: 199 (!= 1029)"
> DEBUG[12-13|19:30:48.307] Message handling failed in `snap`        peer=9f7c9fb3 err=EOF
> DEBUG[12-13|19:30:48.307] Ethereum handshake failed                id=9f7c9fb3fbaa28ea conn=dyndial err="network ID mismatch: 199 (!= 1029)"
> DEBUG[12-13|19:30:48.307] Removing p2p peer                        peercount=0 id=9f7c9fb3fbaa28ea duration=151.450ms req=true  err="subprotocol error"
> DEBUG[12-13|19:30:52.267] Removed dead node                        b=13 id=9f7c9fb3fbaa28ea ip=54.241.235.101 checks=0
> DEBUG[12-13|19:30:53.901] NTP sanity check done                    drift=5.098972ms
> INFO [12-13|19:30:58.375] Looking for peers                        peercount=0 tried=4 static=0
> ```

hi,mjay0 .
could you paste the configs files you use? so i can check if something goes wrong.
1.make sure use the mainnet-v1 folder and check the bttc-start.sh file to seed if '--networkid 199' config correct
2. make sure delivery starts correctly. cus bttc block sync will rely on delivery service

**Comment by mjay0** [comment]
Ah my apologies
—networkid=1029 was still in my startup parameters. Problem fixed, closing issue.
